project:
  type: website
  output-dir: ../docs

website:
  title: "Ainsley and Nick Memorial Project"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: memorial_design.ipynb
        text: Memorial Deisgn
      - href: significance.ipynb
        text: Significance to African Conflict and Security
      - href: review.ipynb
        text: Review
      - href: references.ipynb
        text: References


format:
  html:
    theme: materia
    toc: true

